# Generated by Django 4.0 on 2026-02-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_order_canceled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='住所1 丁目・番地・号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='住所2 マンション・アパート名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='市町村'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefecture',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='郵便番号'),
        ),
    ]
