# Generated by Django 4.0 on 2026-02-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_address1_alter_user_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.CharField(default='', max_length=50, verbose_name='住所1 丁目・番地・号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(default='', max_length=50, verbose_name='住所2 マンション・アパート名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='市町村'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefecture',
            field=models.CharField(default='', max_length=50, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(default='', max_length=15, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='', max_length=8, verbose_name='郵便番号'),
        ),
    ]
