# Generated by Django 4.0 on 2026-02-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_address1_alter_user_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='住所2 マンション・アパート名'),
        ),
    ]
